In [1]:
#Import Libraries
import numpy as np
import pandas as pd

In [2]:
pip install tensorflow_datasets

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [4]:
from tensorflow_datasets import datasets

In [5]:
datasets


<module 'tensorflow_datasets.datasets' (<_frozen_importlib_external._NamespaceLoader object at 0x0000018119B32AD0>)>

In [6]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np
import pandas as pd

In [8]:
from tensorflow_datasets import datasets


In [9]:
datasets

<module 'tensorflow_datasets.datasets' (<_frozen_importlib_external._NamespaceLoader object at 0x0000018119B32AD0>)>

In [10]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [11]:
#loaded mnic dataset
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [12]:
x_train #convert the image to 3x3 matrix  

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [13]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [14]:
x_train.shape

(60000, 28, 28)

In [15]:
x_test.shape

(10000, 28, 28)

In [16]:
width,height = 28,28
input_shape=(width,height,1)

In [17]:
input_shape

(28, 28, 1)

In [18]:
#reshaped the dataset
x_train=x_train.reshape(x_train.shape[0],height,width,1)
x_test=x_test.reshape(x_test.shape[0],height,width,1)

In [19]:
x_train.shape

(60000, 28, 28, 1)

In [20]:
y_train.shape


(60000,)

In [21]:
#creation of training and testing set 
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train,test_size=0.1)

In [22]:
len(x_val)

6000

In [23]:
#Normalising Data / Scaling
#Here in ML we are Feature Scaling-some images has value 0 & some images has value 255.
#Different ranges so model focus more on 255 so we have to normalize the data

In [24]:
x_train=(x_train - x_train.mean())/x_train.std()
x_val=(x_val - x_val.mean())/x_val.std()
x_test=(x_test - x_test.mean())/x_test.std()

In [25]:
#encoded labels also into categorical data
from tensorflow import keras
num_labels=10
y_train=keras.utils.to_categorical(y_train)

In [26]:
y_train

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [27]:
y_val=keras.utils.to_categorical(y_val)
y_test=keras.utils.to_categorical(y_test)

In [28]:
#BUILD OUR MODEL

In [29]:
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

In [30]:
#Created model using Lenet 5_architecture

In [31]:
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

In [32]:
model=Sequential()

In [33]:
model.add(Conv2D(6, kernel_size=(5,5), strides=(1,1), activation='tanh', input_shape=(28,28,1)))

model.add(AveragePooling2D(pool_size=(2,2),strides=(1,1)))

model.add(Conv2D(16,kernel_size=(5,5),strides=(1,1),activation='tanh'))

model.add(AveragePooling2D(pool_size=(2,2),strides=(2,2)))

model.add(Conv2D(120,kernel_size=(5,5),strides=(1,1),activation='tanh'))

model.add(Flatten()) 
model.add(Dense(84,activation='tanh'))
model.add(Dense(num_labels,activation='softmax'))

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (Average  (None, 23, 23, 6)         0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Avera  (None, 9, 9, 16)          0         
 gePooling2D)                                                    
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten (Flatten)           (None, 3000)              0

In [35]:
from keras import metrics

In [42]:
model.compile(loss = keras.losses.categorical_crossentropy,optimizer = 'adam' , metrics = ['accuracy'])


In [43]:
history=model.fit(x_train,y_train,batch_size=32,epochs=20,verbose =1,validation_data=(x_val,y_val))

Epoch 1/20
1688/1688 [==============================] - 35s 20ms/step - loss: 0.2052 - accuracy: 0.9386 - val_loss: 0.1269 - val_accuracy: 0.9630
Epoch 2/20
1688/1688 [==============================] - 33s 20ms/step - loss: 0.0954 - accuracy: 0.9709 - val_loss: 0.1082 - val_accuracy: 0.9653
Epoch 3/20
1688/1688 [==============================] - 33s 20ms/step - loss: 0.0779 - accuracy: 0.9765 - val_loss: 0.0801 - val_accuracy: 0.9760
Epoch 4/20
1688/1688 [==============================] - 35s 21ms/step - loss: 0.0720 - accuracy: 0.9783 - val_loss: 0.0746 - val_accuracy: 0.9780
Epoch 5/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.0645 - accuracy: 0.9803 - val_loss: 0.0701 - val_accuracy: 0.9785
Epoch 6/20
1688/1688 [==============================] - 34s 20ms/step - loss: 0.0610 - accuracy: 0.9811 - val_loss: 0.0682 - val_accuracy: 0.9800
Epoch 7/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.0567 - accuracy: 0.9828 - val_loss: 0.0690 -

In [ ]:
#testing_model

In [44]:
score=model.evaluate(x_test,y_test,verbose=1)

313/313 [==============================] - 3s 8ms/step - loss: 0.0426 - accuracy: 0.9868


In [45]:
score


[0.042620230466127396, 0.9868000149726868]